[package]
name = "schema-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
config-model = { path = "../../crates/config-model" }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
