schema_version: 1
project: supervisor-demo

# Routing configuration for M7
routing:
  enabled: true
  default_timeout_ms: 5000
  broadcast_mode: "oneshot"

agents:
  - name: supervisor-agent
    role: supervisor
    provider: claude
    model: sonnet-4
    system_prompt: "You are a supervisor agent. Monitor and report on agent activities."
    allowed_tools: []
  - name: backend-dev
    role: backend
    provider: gemini
    model: gemini-1.5-flash
    system_prompt: "You are a backend developer. Implement API endpoints."
    allowed_tools: ["Edit", "Bash(git:status)"]
  - name: frontend-dev
    role: frontend
    provider: cursor-agent
    model: gpt-5
    system_prompt: "You are a frontend developer. Build user interfaces."
    allowed_tools: ["Edit", "Search"]
  - name: devops-engineer
    role: devops
    provider: claude
    model: sonnet-4
    system_prompt: "You are a devops engineer. Manage infrastructure and deployments."
    allowed_tools: ["Bash(docker:build)", "Edit"]