[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
serde_json = "1"
thiserror = "2"
 time = { version = "0.3", features = ["formatting", "macros"] }
tempfile = "3"
config-model = { path = "../config-model" }
